## Numerical Python

In [1]:
import numpy as np

In [2]:
arr = np.array([12,23,45,56,32])

In [3]:
arr

array([12, 23, 45, 56, 32])

In [4]:
print(arr)

[12 23 45 56 32]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.dtype

dtype('int32')

In [8]:
arr = np.array([12,23,45,56,32,66.22])

In [9]:
arr.dtype

dtype('float64')

In [10]:
arr

array([12.  , 23.  , 45.  , 56.  , 32.  , 66.22])

In [13]:
arr = np.array([12,23,45,56,32,66.22,'Pune'])

In [14]:
arr

array(['12', '23', '45', '56', '32', '66.22', 'Pune'], dtype='<U32')

In [15]:
arr.dtype

dtype('<U32')

In [19]:
%%timeit
arr = np.array([12,23,45,56,32,66.22,'pune'])

1.63 µs ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
arr[3]

'56'

In [23]:
arr.shape

(7,)

In [25]:
arr = np.array([12,23,45,56,32])
arr * 2

array([ 24,  46,  90, 112,  64])

In [26]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.arange(2,20,2.5)

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

In [30]:
range(2,20,2.5) # we cannot use difference of float value in rangbe but in arange we can use 

TypeError: 'float' object cannot be interpreted as an integer

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.twos(10)  # we can use only  in one and zeros

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [38]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
arr1.ndim # check the dimention of a array

2

In [41]:
arr1.flatten() # to convert multidimention too one dimentional 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr1.shape

(4, 3)

In [43]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr1.size

12

In [45]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
arr1.reshape(6,-1) # when you don't know the number of rows or columns
                   # -1 will sort according to it 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [49]:
arr1.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [52]:
arr1.reshape(3,2,-1)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [53]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [54]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
arr1[0:3,0:2] # to access specific elements in rows and columns
              # First operations for rows and second for columns 

array([[1, 2],
       [4, 5],
       [7, 8]])

In [58]:
arr

array([12, 23, 45, 56, 32])

In [60]:
arr.mean()

33.6

In [61]:
arr.min()

12

In [62]:
arr.max()

56

In [64]:
arr = np.array([1,2,3,4,5,3,1,7])

In [66]:
np.unique(arr) # used to display only unique values and not the repeated values 

array([1, 2, 3, 4, 5, 7])

In [67]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
np.linalg.det(arr2) # linalg = linear algebra

6.66133814775094e-16

In [72]:
np.linalg.inv(arr2)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [74]:
arr1 @ arr2 # for cross product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])

In [77]:
arr3 = np.array([[1,2,3],[4,5,6],[10,11,12]])

In [78]:
arr3 * arr2 # for dot product

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 70,  88, 108]])